### ISSUE TITLE
undo/redo feature for timeline editor

### ISSUE THREAD

**Issue by Schwender-exe** [coppolaemilio/dialogic#426] opened 2021-07-29 03:58 UTC
some form of undo/redo within the timeline editor would be helpful, I've accidentally deleted entire nodes of dialogue accidentally by pressing backspace a few too many times and with no way of undoing it I end up having to re-write it.
obviously not an _asap_ feature, but one that would be very much appreciated!

**Comment by coppolaemilio-farmersfridge** [comment] 2021-07-29 04:00
yeah, it should be fixed asap.

**Comment by coppolaemilio** [comment] 2021-07-29 04:01
Yeah, it should be fixed asap. I'll add it to the 1.3 milestone

**Comment by Jowan-Spooner** [comment] 2021-07-29 06:46
Kind of a duplicate of #321. But I agree. Maybe I can do this today. Already implemented it halfway once.

**Comment by Jowan-Spooner** [comment] 2021-07-29 09:51
Small status update:
- Deleting, Cutting and Pasting can now be redone on my branch.

Will be working on Event Adding, moving and duplicating next.

**Comment by Jowan-Spooner** [comment] 2021-07-29 15:03
Hey @Schwender-exe (and @coppolaemilio) please check out my attempt at implementing this #428. As always when testing things, make a copy of your project or create a new one. 

Hope it works!

**Comment by coppolaemilio** [comment] 2021-08-04 22:32
Tested this a lot and tried to break it but it seems pretty solid. The only issues I found were mixing some copy and paste from text and events but it is better to see those errors than to lose an event. 

Thank you so much once again @Jowan-Spooner 🙇🏻 

Closing the issue now, but feel free to re-open or comment

**Closed by coppolaemilio** 2021-08-04 22:32 UTC
Labels: enhancement
