### ISSUE TITLE
Test Style Button Uses Wrong Style

### ISSUE THREAD

**Issue by exelia-antonov** [coppolaemilio/dialogic#1833] opened 2023-10-27 18:09 UTC
Using the Test Style button in the editor doesn't test the actual current style, but runs a test scene with the default style instead

**Comment by Jowan-Spooner** [comment] 2023-10-30 12:32
Not sure what you problem is. It works fine for me.

**Comment by Jowan-Spooner** [comment] 2023-12-02 13:32
I'll close this as I cannot reproduce it.

**Closed by Jowan-Spooner** 2023-12-02 13:32 UTC
Labels: Bug 🐞
