### ISSUE TITLE
Dialog position is wrong when current camera is moving

### ISSUE THREAD

**Issue by HarleyDavidson86** [coppolaemilio/dialogic#331] opened 2021-06-01 13:04 UTC
## The problem

**Describe the bug**
I have a scene which is larger than the current viewport. So the active camera is moving when player goes to the right
and following him. When the camera viewport is on the right, the dialog stays on the old screencenter.
set_position or set_global_position doesn't seem to have an effect placing it right.

**To Reproduce**
1. Create a scene with a camera
2. Move the camera to the right and set it to "current"
3. Add a dialog

**Expected behavior**
The dialog should be centered on screen or it reacts correctly when setting global_position or current camera moves

**Screenshots**
This is how it should be:
![should](https://user-images.githubusercontent.com/16794874/120327317-ea5c0600-c2e9-11eb-9dcf-a5cdb5faf7dd.png)
This is how it looks when camera is moving away: 
![actual](https://user-images.githubusercontent.com/16794874/120327417-05c71100-c2ea-11eb-94a2-4f5e1fed353e.png)

## Solutions

**Workaround**
My workaround is create the dialog under a CanvasLayer-Node in the scene.

**Comment by coppolaemilio** [comment] 2021-06-01 13:30
It seems like you need to add Dialogic as a child of a CanvasLayer node.
If you use version 1.2 this is done automatically for you :)

Closing because it is not a bug and this has been fixed, hopefully I will be able to release 1.2 stable soon 😅

**Closed by coppolaemilio** 2021-06-01 13:30 UTC
Labels: bug
