### ISSUE TITLE
(Minor) Blank display name causes bbcode issue with name coloring

### ISSUE THREAD

**Issue by Proggle** [coppolaemilio/dialogic#638] opened 2021-11-24 00:02 UTC
## If you set a character's display name to an empty string, dialogic will show the name coloring bbcode when it shouldn't.

To reproduce:
Set display name to blank
![image](https://user-images.githubusercontent.com/89282845/143147504-adee32d5-059d-4acc-b720-29db26385190.png)

Result
![image](https://user-images.githubusercontent.com/89282845/143147398-29d2e299-8341-4415-82ff-33cbe2e63042.png)

**Comment by Jowan-Spooner** [comment] 2021-11-24 06:22
Probably already fixed in 1.4, as it sounds like a duplicate of #526

**Comment by Proggle** [comment] 2021-11-24 06:58
> Probably already fixed in 1.4, as it sounds like a duplicate of #526

Ah, I thought I was on the latest since I grabbed it from the asset library again, but looks like the asset library hasn't got 1.4 yet.  I'll see if I can grab the latest build and try it.

**Comment by Jowan-Spooner** [comment] 2021-11-24 07:09
1.4 is WIP, that's why its not on the asset library. Feel free to try it out, but there might be bigger  changes before release

**Comment by Jowan-Spooner** [comment] 2021-11-28 09:52
I think this is fixed, if not we can reopen this.

**Closed by Jowan-Spooner** 2021-11-28 09:52 UTC
Labels: Bug 🐞
