### ISSUE TITLE
I cannot select characters on the timeline

### ISSUE THREAD

**Issue by Negumi01** [coppolaemilio/dialogic#1530] opened 2023-04-24 08:20 UTC
I cannot select characters on the timeline, when I try to select characters on the Text or Character property, nothing shows down and these bugs' messages appear:

> The object does not have any 'meta' values with the key 'dialogic_character_directory'.
> res://addons/dialogic/Events/Text/event_text.gd:233 - Trying to assign value of type 'Nil' to a variable of type 'Dictionary'.

Screenshots
![image](https://user-images.githubusercontent.com/85794474/233939504-17349df5-2388-43a6-99a3-6e46095a0c8a.png)

System
 - OS: Windows 11
 - Godot Version: 4.0.2
 - Dialogic Version: 2.0

**Comment by coppolaemilio** [comment] 2023-04-24 08:24
Can you upload the project you are using? So that we can test and see what the issue is. Thanks!

**Comment by Jowan-Spooner** [comment] 2023-05-20 11:12
Cannot reproduce without help or more clear directions of what you've done before getting the error.
I will close this if no more info is provided, as selecting characters works at least most of the time.

**Closed** 2023-07-31 09:14 UTC
Labels: Bug 🐞, Needs testing
