### ISSUE TITLE
Build problem Godot 3.4.4

### ISSUE THREAD

**Issue by jacksonwilliampluskota** [coppolaemilio/dialogic#968] opened 2022-06-29 12:05 UTC
when i using in Dialogic in godot it's work fine but when  i build the dialog don't run

What i did
I maked a simple dialog
![image](https://user-images.githubusercontent.com/10143574/176430664-00d4de0c-0717-436b-b2cd-026605bbf7c7.png)

and in engine run worked well
![image](https://user-images.githubusercontent.com/10143574/176430882-efb4d197-690a-41b4-bbf8-f4dea842d8eb.png)

 but when i build the game using the filter to export

![image](https://user-images.githubusercontent.com/10143574/176431094-468d3c83-dcb5-4fd9-81f3-6eefcc03e505.png)

not worked in build gave me this error
![image](https://user-images.githubusercontent.com/10143574/176431264-f65a9d04-90fa-4771-87f3-c9b84fa62891.png)

i created the dialogue by script
var new_dialog = Dialogic.start('start') 
add_child(new_dialog)

**Comment by Jowan-Spooner** [comment] 2022-06-29 13:08
Probably related to #898 #914. Maybe caused by #915

**Comment by jacksonwilliampluskota** [comment] 2022-06-29 22:08
i just created a new theme and set as default and the build works well.
Thank you very much

**Comment by zaknafean** [comment] 2022-07-06 03:51
This and its dupes should be fixed with #978

**Closed by zaknafean** 2022-07-06 03:51 UTC
Labels: Bug 🐞, Critical 💩
