### ISSUE TITLE
Pressing next-key skips dialogue choice button.

### ISSUE THREAD

**Issue by Eversco** [coppolaemilio/dialogic#764] opened 2022-02-03 19:15 UTC
When dialogue is on the slide where the choice buttons are available, pressing any next key (e.g. space) skips the dialogue thus resulting in no choice being chosen by the user.

**Comment by Jowan-Spooner** [comment] 2022-02-03 19:31
can you give some more information? I cannot reproduce the behaviour. What version are you using? how are your input settings set up?

**Comment by Jowan-Spooner** [comment] 2022-03-13 18:26
@Eversco Please give an update on this, otherwise this will be closed in the future.

**Comment by zaknafean** [comment] 2022-05-22 17:31
2 months, no response. Closing the issue out.

**Closed by zaknafean** 2022-05-22 17:31 UTC
Labels: Bug 🐞
