### ISSUE TITLE
Translate Dialogues

### ISSUE THREAD

**Issue by PonySchreck** [coppolaemilio/dialogic#343] opened 2021-06-05 17:53 UTC
**Is your feature request related to a problem? Please describe.**
At the moment it doesnt seem easy to create games with multiple languages with this plugin.

**Describe the solution you'd like**
It would be great if the Event Editor would have a Translation Tool. E.g. A Dropdown menu where you can select a language to translate to. And if you select a language the nodes stay the same but you could edit the output messages. Dialogic could then check the TranslationServer and output the right Text.

**Describe alternatives you've considered**
It seems possible with a dictionary and translationfiles but this solution seems too clunky and would make the great usability of the event editor senseless just to support mutliple languages.

**Additional context**
I am working on a Game that i would love to export with German and English text. 
I really love the plugin! Thanks for the great work for the community! <3

**Comment by Jowan-Spooner** [comment] 2021-06-07 16:54
Hi thanks for your request. I have to add that this is related and possibly a duplicate of #249, although your suggestion is more concrete.

I'm not quite sure what the standard procedure is to translate games and I'm not sure whether it is done in the editor or an external tool for most games, especially bigger ones. I would guess that many people might like to translate their game into english and there native language directly inside the editor, in a way similar to what you proposed. But for all languages that none of the developers speaks, translating in external files/programms seems more logical (for example to have community translations). So there should also be an option to export the text of the game into a table like format, that can then be translated and imported back into the game. 

Both versions should be considered when designing a strong translation tool/workflow for dialogic, in my opinion.

What do you think?

Also nice, I'm german too ;).

**Comment by zakary93** [comment] 2021-06-16 05:44
Not that I have done it myself, but a standard method that many use is to use (at least on an indie-mid sized studio scale) JSON, XML, or even CSV or something similar in usage to send to freelance translators (which many are familiar with these kinds of file formats) to replace text. They are then inserted in the file directory wherever dialogs go and called when the appropriate language is selected in game settings with the appropriate language suffix (e.g. Dialog1_en.json, Dialog1_jp.json, etc). I agree that having an in-editor translation tool would be helpful, but many times it is just outsourced like I described. Maybe, we could have Dialogic spit out a realistically readable JSON file, then create another dialog which can then read the translated JSON that a translator delivers back as an Event in the editor? (just spitballing here to get better ideas flowing)

**Comment by scottkunkel** [comment] 2021-07-16 19:05
It should use the standard Godot language support. Which allows the use of csv files.
https://docs.godotengine.org/en/stable/tutorials/i18n/internationalizing_games.html

**Comment by idchlife** [comment] 2021-11-11 11:47
Quick localization usage fix for those who doesn't use BBCodes (did not test this with them):

https://github.com/coppolaemilio/dialogic/blob/main/addons/dialogic/Nodes/TextBubble.gd#L65

change this to 

```python
  text_label.bbcode_text = tr(text)
```

This will use Godots localization system

**Comment by scottkunkel** [comment] 2021-11-11 11:55
Might want to include options for questions 

Thomas

**Comment by Linkyu** [comment] 2021-11-22 20:29
There is a small hurdle on this issue: TranslationServer is only available at runtime, so the translation file needs to be parsed manually (which is not hard to do, but it needs to be done smartly).

I've been working on something pretty close to what's wanted here (minus the editing part):

![image](https://user-images.githubusercontent.com/3739611/142930066-2dd31866-f470-497f-bb6d-7e21a9e9bbbf.png)

I'll send a pull request once I finish optimising it.

**Comment by DasCapschen** [comment] 2021-12-01 20:46
This would also need to include translating glossary entries. Both names and texts. Would that be as easy, by just using tr() ?

**Comment by Linkyu** [comment] 2021-12-12 23:53
> This would also need to include translating glossary entries. Both names and texts. Would that be as easy, by just using tr() ?

Oh, good point! I haven't used it yet so I completely forgot about the glossary. Here we go:
![image](https://user-images.githubusercontent.com/3739611/145734317-c46a8d5d-8d78-45cc-a478-303976362e18.png)

But yes it is just as easy as using tr(); the way I've done it is by implementing a translate() function inside DialogicResources that works exactly the same way as tr():

```gdscript
# Translates a message inside the editor based on the translation file provided in the settings
static func translate(key: String):
	# Retrieve the reference dictionary
	var translations := load_json(WORKING_DIR + "/translations.json")
	
	# Check the test locale currently set in the project settings
	var locale = ProjectSettings.get_setting("locale/test")
	if locale == "":
		locale = ProjectSettings.get_setting("locale/fallback")
	
	# Return the translation for that locale if it exists, otherwise simply return the input
	if translations.has(key):
		return translations[key][locale]
	else:
		return key

**Comment by Linkyu** [comment] 2021-12-13 21:51
OK, I hadn't expected the main branch to have changed that much since 1.3 so it took a bit longer tan planned, but I've now sent a pull request (#676).

It doesn't cover the editing part of this issue, but should it be decided for Dialogic to be used as a localisation editor, at least the framework is now available to do so.

**Comment by eh-jogos** [comment] 2022-06-03 15:01
Wouldn't it be easier for dialogic to just generate a "unique_id" for events/glossary that uses text, something readable like `timeline_name_event_id` or `glossary_entry` and use that to export a csv table with the current text as the default locale?

This way the editor would still support just one language, but it wouldn't need to use the TranslationServer, users would be able to use the CSV to easily translate it, or send it to translation pipelines, and on runtime the Dialogic Node or system that grabs the actual text could just return `tr(text_id)` instead of the actual text field.

Sorry if this makes no sense, I haven't used Dilogic yet, just was exploring the documentation and the plugin to see if it's a good fit to replace a DialogueSystem in another project, but that project does need localization.

**Comment by Jowan-Spooner** [comment] 2022-07-03 17:04
You can now create translations for Dialogic 2.0. Although part of the process is automated, the acutal translation has to happen outside of godot (they are csv files). If people really want a built-in translation editor, we could consider it, but I would rather have someone open a new issue for that.

**Closed by Jowan-Spooner** 2022-07-03 17:04 UTC
Labels: Feature✨
