### ISSUE TITLE
Per-Character Typing Audio / Default Per-Character Themes

### ISSUE THREAD

**Issue by Aurora-Eluvia** [coppolaemilio/dialogic#668] opened 2021-12-06 20:00 UTC
**Is your feature request related to a problem? Please describe.**
When running a scene, I'd like for each character to have their own default settings for typing sounds.

**Describe the solution you'd like**
Ability to set specific audio typing settings per character as defaults that take precedence over the Theme default.

**Describe alternatives you've considered**
Creating themes for each character and swapping them in whenever they are speaking so that they have their own sound effects is presently my only option, as far as I'm aware. Not horrible, honestly, but it would mean I'd have to make sure I didn't miss one per character. It would also mean that any changes I made to one theme would have to be replicated in all of the other themes in order to maintain consistency.

Alternative/In addition?: Being able to set a default theme per character with all the fixings, not just for audio speed, but I'd like the option to do both if possible, or to have it be the default but allow me to set local variations that take precedence for _any_ setting.

The theme default could be good for a "narrator" voice where no character is speaking, and it gets overridden by character-specific ones.

**Additional Context**
For an example of this in action, Deltarune appears to use a basic beep that's just transformed various ways for its different characters, each of whom has a unique "voice" that comes through in the typing.

While this is possible with Dialogic, there are extra steps that make it a little more tedious.

**Comment by Jowan-Spooner** [comment] 2021-12-13 17:31
Thanks for the request.
Agreed that this would be cool. This is a duplicate of #364 tho, if I'm not mistaken. I believe @timkrief wanted to implement this, but I'm not sure what the state of that is at the moment. 

I'll close this issue, but the feature itself is on the to do list.

The very long to do list...

**Closed by Jowan-Spooner** 2021-12-13 17:31 UTC
