### ISSUE TITLE
Nice Names For Enums

### ISSUE THREAD

**Issue by exelia-antonov** [coppolaemilio/dialogic#1222] opened 2022-09-14 02:44 UTC
Enums by default don't have text names to them. it'll be easier to use them in text timelines with text values, instead of having to rememember the numbers

![image](https://user-images.githubusercontent.com/2214793/190046399-2514542a-df0a-4fb4-968f-ab8fdc777921.png)

![image](https://user-images.githubusercontent.com/2214793/190046361-40be1638-bf6c-458f-88b3-3192051f1313.png)

**Comment by thebardsrc** [comment] 2022-09-14 02:52
might need to change them from being enums to implement. some languages you can set strings for enums for serialization/deserialization, Godot 3.x you could, but looks like enum was changed in GDScript 2.0 to be strictly ints

**Comment by Jowan-Spooner** [comment] 2022-09-14 16:31
This is somewhat a duplicate of #1133, at least I was trying to describe the same problem as this one. This is a much better explenation though. 
One other thought I had, was that I would love to optionally be able to name positions too. Like left, center, right instead of 1,3,5. Would lead to much more readable timelines as well. But positions and where they are is very project dependant, so it would need a different fix.

**Comment by thebardsrc** [comment] 2022-09-15 01:17
for the latter, that seems simple enough, we can just add an optional string value to `class_name DialogicNode_PortraitPosition` as well as the int `position_index`. then they could name it in the dialognode if they want to do that, and use it by either name or by number

**Closed** 2023-08-30 11:04 UTC
Labels: Noob Friendly 👍, UI/UX ✏, Not Critical 🏖
