### ISSUE TITLE
Selectors in the ui are not working

### ISSUE THREAD

**Issue by delleloper** [coppolaemilio/dialogic#354] opened 2021-06-12 14:36 UTC
## The problem

When i click on the button to select a character or any other selector like set value, it chages the dialogic editor to the 2d editor

**To Reproduce**

Add any funcion, that has a selector,  like a text event and click the selector to change the character

**Expected behavior**

It should display the correspondent list of elements

**Screenshots**

https://media.giphy.com/media/VoDdKeYSsAOBmg6Yay/giphy.gif

**System (please complete the following information):**
 - OS: Win 10
 - Godot Version: 3.3.2
 - Dialogic Version: 1.2

**Possible fixes**

Godot console threw:
WARNING: BaseButton's Enabled Focus Mode property has been deprecated due to redundancy and will be removed in Godot 4.0. Please use Control.set_focus_mode instead.

**Comment by delleloper** [comment] 2021-06-12 14:56
I downladed the souce from the repo, the last commit was "making the character optional to make script timelines easier" and now i works

**Comment by Jowan-Spooner** [comment] 2021-06-13 15:44
Hey @delleloper thanks for writing it down. Afaik both emilio and I have encountered this bug. But it always goes away if you disable and enable the plugin once or twice, so I really have no idea what it could be. 

If anyone has an idea what could be the issue, please make us know.

**Comment by coppolaemilio** [comment] 2021-06-14 11:38
I hope this error will go away magically when we simplify and refactor most of the elements. But it seems to be an issue with how Godot instanced scenes work on plugin (tool) scripts. My guess is that it fails to get the proper references when initialized and it automatically fails when they try to populate the dropdowns. We will see what can be done 😩

**Comment by Sslaxx** [comment] 2021-06-18 11:51
If it's an issue with Godot, has it been reported there?

**Comment by coppolaemilio** [comment] 2021-06-18 11:55
We are still not sure what the source of the issue is, but every time I encounter a Godot bug I report it on the official repo 👍🏻

**Comment by Lighar** [comment] 2021-07-15 10:30
I got the same problem recently,
After testing several cases, it seems that in my case it only happens if a node of my 2D scene is selected when I try to select the character.
In the case where no node is selected, the selection works without problem.
Although I don't know if this is a general case or only mine

**Comment by coppolaemilio** [comment] 2021-07-15 10:33
This was fixed in the version 1.2.5, I will do an official release either today or tomorrow :)

**Closed** 2021-07-15 10:33 UTC
Labels: bug
