### ISSUE TITLE
Selecting timeline from the editor crashes Godot

### ISSUE THREAD

**Issue by MagusWazir** [coppolaemilio/dialogic#534] opened 2021-09-26 02:00 UTC
## The problem

**Describe the bug**
Trying to access timelines will cause Godot to crash. 

**To Reproduce**
1. Create a new timeline
2. Run scene or click away to a different tab
3. Try to view timeline again
4. Godot Crashes

**Expected behavior**
I should be able to view and edit timeline if clicking on it and Godot should keep running

**Screenshots**

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.2.1
 - Dialogic Version: 1.2.5

## Solutions

**Workaround**

Reverting to previous version

**Possible fixes**

**Comment by Jowan-Spooner** [comment] 2021-09-28 18:38
This is a realy strange bug. Could you try it out with the 1.3 WIP branch? Make sure to use a test project or make a backup of your project!

**Comment by coppolaemilio** [comment] 2021-10-01 11:18
Can't reproduce 🤔

**Comment by Jowan-Spooner** [comment] 2022-02-06 10:58
I will close this, as I cannot reproduce it either. If you can provide a way to still reproduce this bug, feel free to reopen it.

**Closed by Jowan-Spooner** 2022-02-06 10:58 UTC
Labels: Bug 🐞
