### ISSUE TITLE
some form of Goto event for timeline?

### ISSUE THREAD

**Issue by Schwegg** [coppolaemilio/dialogic#434] opened 2021-07-30 03:57 UTC
would love for some form of Goto event with a secondary event which would act as a bookmark for the Goto event to select from possibly?

**Comment by Jowan-Spooner** [comment] 2021-07-30 05:31
Hey I agree this would be cool.
It's related to if not a duplicate of #325. I thought of your bookmarks as anchors. It's quite a bit of work tho. We'll see if it actually makes it into 1.3.

**Comment by Jowan-Spooner** [comment] 2022-02-06 11:05
This became reality! In 1.4 we have the Go To and the Label event that allow exactly this!

**Closed by Jowan-Spooner** 2022-02-06 11:05 UTC
Labels: Improvement✨
