### ISSUE TITLE
Text input box width incorrect for first ~30 characters

### ISSUE THREAD

**Issue by chrisk-7777** [coppolaemilio/dialogic#847] opened 2022-03-24 09:52 UTC
## The problem

**Describe the bug**

The first 30 characters of the input box are cropped. It appears the width of the input isn't autosizing. I've provided a video below. This is on an empty project. 

**To Reproduce**
1. Go to Dialogic
2. Click on New timeline
3. Click "Text"
4. Type words into input
5. Wait for it to jump to right width after 20 to 30 characters

**Expected behavior**
All text should be visible from start

**Screenshots**

https://user-images.githubusercontent.com/55621012/159889368-c8a2b76e-1e98-4753-b97e-94f1efd9344c.mp4

**System (please complete the following information):**
 - OS: Mac M1 
 - Godot Version: 3.4.3
 - Dialogic Version: 1.4.1

## Solutions

**Workaround**

If i keep typing eventually it auto sizes

**Possible fixes**

Hmm, I'm not too sure....

**Comment by Jowan-Spooner** [comment] 2022-03-24 20:13
Sorry, I cannot recreate this. 
Are you possible using a HiDPI monitor or have changed anything about the theme?

**Comment by chrisk-7777** [comment] 2022-03-24 23:22
> Sorry, I cannot recreate this. Are you possible using a HiDPI monitor or have changed anything about the theme?

Thanks for checking Jowan. This is on a fresh project with no theme changes. 

[My primary monitor is](https://www.lg.com/au/it-monitors/lg-29UM65):
```
LG ULTRAWIDE Display
28.5-inch (2560 x1080)
```

And secondary monitor is (laptop screen):
```
Built-in Liquid Retina DR Display
14-inch (3024 x1964)
```

The issue occurs on both. I'm 90% sure the ultrawide isn't HiDPI

**Comment by coppolaemilio** [comment] 2022-03-25 13:37
It is interesting. I see that the background of your panels are dark green? Do you have any custom theme settings in the editor? have you tried using the default style?

**Comment by chrisk-7777** [comment] 2022-03-25 13:52
Hey coppolaemilio - I just tried switching back to the default Godot theme, but unfortunately the same thing. 

I've recorded a video with a completely fresh project and the theme reset to the default. 
I had to upload to YT because of the size (its still processing the HD, so you may need to refresh in a few minutes if its not clear enough). 

https://www.youtube.com/watch?v=VtMRmr49DTo

Again, if I'm the only one getting this I'm happy to close it, it might be some particular setup on my machine only causing it

**Comment by coppolaemilio** [comment] 2022-03-25 14:13
Thanks for the video! Don't close the issue, I think it should be interesting to figure out what is wrong and how we can fix it. I'll try it out on my M1 mac to see how it looks like there

**Comment by thebardsrc** [comment] 2022-03-25 23:35
I can confirm on my M1 Mac that it does indeed do this same thing.

it appears that its not detecting the width for the box correctly to scale it, and wrapping it into multiple lines. as the video demonstrates there, its very small at first, then clicking out and going to the timeline again its bigger but still not actually correct. screenshot from my mac: 
<img width="431" alt="Screen_Shot_2022-03-25_at_5 26 36_PM" src="https://user-images.githubusercontent.com/2214793/160214360-47950d59-514d-46ca-8853-7f6ac2644a12.png">

and while not the same thing exactly, I've also noticed similar issues with the scaler on my PC as well (which is also a HiDPI laptop), where instead the box scaler will just randomly (meaning most of the time its fine) treat a multi-line box as only one line high, with its own separate scrollbar. I think this is the same issue in another form:
<img width="419" alt="Capture" src="https://user-images.githubusercontent.com/2214793/160214631-efe88e4a-00a1-4a52-96fe-f2e7cc86b76b.PNG">

**Comment by endaye** [comment] 2022-04-05 06:19
My mac M1 has the same issue with Chinese text.
<img width="524" alt="image" src="https://user-images.githubusercontent.com/4829591/161690990-e2d01b96-2e8e-4adb-8329-271a4e79a556.png">

**Comment by coppolaemilio** [comment] 2022-04-11 12:10
@thebardsrc @chrisk-7777 @endaye can you check if the latest merge I did fixed the issue? If it still exists feel free to reopen the issue

**Closed** 2022-04-11 12:09 UTC
Labels: Bug 🐞, UI/UX ✏

**Comment by chris-workinggears** [comment] 2022-04-11 12:19
> @thebardsrc @chrisk-7777 @endaye can you check if the latest merge I did fixed the issue? If it still exists feel free to reopen the issue

Whoop! "1.4.2 - Dev" fixed up the issue 🤘

![image](https://user-images.githubusercontent.com/101536429/162737817-14168cbc-5298-432c-b756-ca636a714452.png)

**Comment by chrisk-7777** [comment] 2022-04-11 12:20
> @thebardsrc @chrisk-7777 @endaye can you check if the latest merge I did fixed the issue? If it still exists feel free to reopen the issue

Whoop! "1.4.2 - Dev" fixed up the issue 🤘

![image](https://user-images.githubusercontent.com/101536429/162737817-14168cbc-5298-432c-b756-ca636a714452.png)
