### ISSUE TITLE
Error appears whenever I enable the plugin

### ISSUE THREAD

**Issue by matiwierzba** [coppolaemilio/dialogic#35] opened 2021-01-25 23:52 UTC
Hi, whenever I import and enable the plugin in a project the following error appears:
res://addons/dialogic/Editor/EditorTheme.gd:43 - Invalid get index 'theme_font' (on base: 'Dictionary').
I tried it both on the current stable version of Godot and on the latest beta version. I also tried it on multiple projects and the result is always the same.
Cheers

**Comment by coppolaemilio** [comment] 2021-01-26 00:47
I can't reproduce this error, what version of Godot and what OS are you running?

**Comment by SexyVetra** [comment] 2021-01-26 07:48
I encountered this error while checking a look at Dialogic today.

OS: Win64 20H2
Godot Version: 3.2.4 beta6 Win64
Dialogic Version: 0.8 downloaded from github

It looked to me like the initial settings are empty because of an empty settings dictionary in the output. After toggling a value in the theme editor to cause the settings to save (I assume and iirc, seeing the settings dict in the output), I was able to start the application again without error.

**Comment by SexyVetra** [comment] 2021-01-26 08:16
This issue is resolved by 058267381bcc17c7ae74963fadb50e0cabccb229 which adds a check on the existence of the settings file and then returns the defaults if it's not present. In the 0.8 release, the defaults are applied and then if the settings file does not exist, the entire settings dictionary is emptied before being returned.

Using a new godot project with the Dialogic 0.8 release reproduces this issue. Replacing only the [load_settings implementation](https://github.com/coppolaemilio/dialogic/blob/master/addons/dialogic/Other/DialogicUtil.gd#L36) from HEAD the issue no longer reproduces.

**Comment by matiwierzba** [comment] 2021-01-26 09:56
I am using Windows 10 64 bit and Godot 3.2.4 beta6. I toggled the value like SexyVetra described and now it's working for me too.

**Closed** 2021-01-27 15:04 UTC
