### ISSUE TITLE
Fade-In time only affects the default theme

### ISSUE THREAD

**Issue by youdin1** [coppolaemilio/dialogic#453] opened 2021-08-10 13:06 UTC
## The problem

**Describe the bug**
When having multiple themes, you can't set an individual time value for each respective theme. Changing the time value for one theme, changes the time value for all of them. Additionally, even when changing the time value for something that isn't set as the default theme, it won't change the in game behavior and will instead resort to whatever the original time value that the default theme had (before being changed), so the value seen in the dialogic editor won't even be what the is happening in the game.
This is really similar to #404 , and both bugs might even come from the same code, I just wanted to make this bug acknowledged!

**To Reproduce**
1. Create a default theme, and set the time value for the fade-in animation to 5
2. Create another theme, and set the time value for the fade-in animation to be 0.5. Now look back to the default theme and see the time value get changed to 0.5.
3. Also, If you create a timeline, and use 'Set Theme' on a custom theme, the animation won't just play the wrong background before changing. The total time for the animation will be 5, not 0.5, which is what is seen in the editor

**System (please complete the following information):**
 - OS: Windows 10
 - Godot Version: 3.3.2.stable
 - Dialogic Version: 1.2.5

## Solutions

**Workaround**

The only solution so far, that I can do myself, is to accept the situation and use a collective fade in animation for every single theme.
I did try to manually configure the code, to check for what theme the node is using, and then use custom tween animations on function 'open_dialog_animation', but I gave up on it when I figured out that the theme gives out inconsistent Config Files 

**Possible fixes**

My guess would be that, just like the #404 issue, that the setting of the theme is registered after the fade-in animation is played, which results in the default themes background and settings being used, rather than the custom theme one wants to have.
As for the inconsistent editor time value, I don't have any other idea where the issue could lie, other than the ThemeEditor node having 'animation_show_time' connected to the '_on_generic_value_change' and it updates too frequently? But that would just be my uneducated guess, since I haven't looked into the other stuff and the issue could come from somewhere else.

**Comment by coppolaemilio** [comment] 2021-09-05 18:40
I think the issue is fixed with my last push, if you find anything feel free to comment and reopen the bug report. Thanks!

**Closed by coppolaemilio** 2021-09-05 18:40 UTC
Labels: bug
