### ISSUE TITLE
Using DialogNode makes the dialog object incorrectly sized

### ISSUE THREAD

**Issue by Crystalwarrior** [coppolaemilio/dialogic#42] opened 2021-01-31 13:53 UTC
With this setup:
![image](https://user-images.githubusercontent.com/3470436/106386146-afea6700-63e4-11eb-849a-2e97af410211.png)
Whenever the game is launched, the dialog node appears disappeared - however, it is simply incorrectly sized. This is caused by `resize_main()` being called in `_ready():`

![WHXKM4z8MY](https://user-images.githubusercontent.com/3470436/106485963-345ee780-64c2-11eb-90a7-bcaad6476984.gif)

When looking into the scene structure using the `Scene/Remote` tab in the engine, it appears that the dialogue node was not destructed, however, it's size is incorrect and way bigger than it is supposed to:
![Godot_v3 2 4-rc1_win64_cBva1PdGZG](https://user-images.githubusercontent.com/3470436/106485987-3aed5f00-64c2-11eb-94ba-6600ea70c243.png)

**Comment by coppolaemilio** [comment] 2021-01-31 23:39
Can't reproduce.

**Comment by Crystalwarrior** [comment] 2021-01-31 23:42
> Can't reproduce.

Will make a video of it

**Comment by Crystalwarrior** [comment] 2021-02-01 16:20
> 
> 
> Can't reproduce.

I have an idea why - is your Dialogic development project's window size 2048 x 1200?
Since I'm using a window size smaller than that, perhaps that could be it.

**Comment by AnidemDex** [comment] 2021-02-17 22:33
Can't reproduce on 0.9

**Comment by AnidemDex** [comment] 2021-02-19 03:59
Hey @Crystalwarrior , I made [resizables dialogs](https://github.com/AnidemDex/dialogic/tree/canvas_hotfix), can you check if it works for you to make a PR that solves this issue?

**Comment by coppolaemilio** [comment] 2021-03-08 15:26
Responsiveness is not planned at the moment, but with new theme properties to make the dialog size smaller and a fix to the resizing on '2D' mode I will close this ticket for now. If responsive sizing is required later in the future a new issue can be created. Thanks!

**Closed by coppolaemilio** 2021-03-08 15:26 UTC
