### ISSUE TITLE
Error messages and empty timeline

### ISSUE THREAD

**Issue by erikbgithub** [coppolaemilio/dialogic#1608] opened 2023-06-18 21:52 UTC
## The problem

**Describe the bug**
The timeline is empty and cannot be modified. Errors show up:
```
E 0:00:01:0154   subsystem_text.gd:399 @ modifier_random_selection(): Condition "p_ptr == nullptr" is true.
  <C++ Source>   core/os/memory.cpp:148 @ free_static()
  <Stack Trace>  subsystem_text.gd:399 @ modifier_random_selection()
                 subsystem_text.gd:288 @ parse_text_modifiers()
                 subsystem_text.gd:67 @ update_dialog_text()
                 subsystem_text.gd:32 @ clear_game_state()
                 DialogicGameHandler.gd:156 @ clear()
                 DialogicGameHandler.gd:54 @ _ready()
```

```
E 0:00:01:0154   subsystem_text.gd:254 @ parse_text_effects(): Condition "p_ptr == nullptr" is true.
  <C++ Source>   core/os/memory.cpp:148 @ free_static()
  <Stack Trace>  subsystem_text.gd:254 @ parse_text_effects()
                 subsystem_text.gd:68 @ update_dialog_text()
                 subsystem_text.gd:32 @ clear_game_state()
                 DialogicGameHandler.gd:156 @ clear()
                 DialogicGameHandler.gd:54 @ _ready()
```

**To Reproduce**

Install Dialogic 2.0 Alpha 8 into Godot v4.0.3.stable.arch_linux and create a new timeline.

**Expected behavior**
No errors and can create timeline.

**System (please complete the following information):**
 - OS:
   ```
   cat /etc/os-release
   File: /etc/os-release
   NAME="Garuda Linux"
   PRETTY_NAME="Garuda Linux"
   ID=garuda
   ID_LIKE=arch
   BUILD_ID=rolling
   ANSI_COLOR="38;2;23;147;209"
   HOME_URL="https://garudalinux.org/"
   DOCUMENTATION_URL="https://wiki.garudalinux.org/"
   SUPPORT_URL="https://forum.garudalinux.org/"
   BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
   PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
   LOGO=garudalinux
   ```
 - Godot Version: v4.0.3.stable.arch_linux
 - Dialogic Version: 2.0 Alpha 8

**Comment by rassweiler** [comment] 2023-06-19 16:26
The null ptr error may not be relate to being unable to edit timelines. I have those but can edit timelines.

I've had ui issues like that when updating the dialogic files without first disabling the plugin, or sometimes I need to delete the import files in the .Godot folder, to refresh the addon after downloading a newer version.

**Comment by Jowan-Spooner** [comment] 2023-06-26 09:19
The nullptr seems to be a problem with regex on archlinux that should be fixed for godot 4.1 (https://github.com/godotengine/godot/issues/76174).

I'm not sure why you cannot edit timelines though. When exactly are you getting these errors? When you press the "Create Timeline" button?

**Comment by Jowan-Spooner** [comment] 2023-08-26 08:24
@erikbgithub are you still having these problems with godot 4.1 and the main dialogic branch?

If you can't test this or reproduce this I'd like to close this issue as it is likely outdated.

**Comment by Jowan-Spooner** [comment] 2023-08-30 09:08
I'll close this for now. If the same errors occur again, we can reopen this.

**Closed by Jowan-Spooner** 2023-08-30 09:08 UTC
Labels: Bug 🐞, Needs testing
