### ISSUE TITLE
Allow using custom choice button container

### ISSUE THREAD

**Issue by fmenozzi** [coppolaemilio/dialogic#449] opened 2021-08-08 02:12 UTC
**Is your feature request related to a problem? Please describe.**
Currently (v1.2.5), choice buttons are arranged in a vertical layout. This is a good default choice, as it will usually allow for more choices to fit on the screen at once, but there might be scenarios (especially for simple "yes/no"-style choices) where it would be desirable to use a horizontal layout instead.

**Describe the solution you'd like**
Allow the user to specify custom containers for choice buttons, similar to how they can currently supply custom choice buttons (#247).

**Describe alternatives you've considered**
A simpler interface could instead ask whether the layout be horizontal or vertical, as these are likely the most common options people would use. The UI could then update based on the selection (e.g. 'vertical separation' would become 'horizontal separation' if the user switches to a horizontal layout). This approach has the benefit of being simpler to use at the cost of less flexibility.

**Additional context**
I discovered Dialogic recently and so far it's quite amazing. It's taken me very little time to replicate my existing dialogue system that I wrote from scratch, and the Dialogic-based solution is generally much more flexible and powerful. However, in my game, my simple yes/no choices are displayed horizontally, and so far I have been unable to figure out whether this is possible in Dialogic (my conclusion so far is that it is not).

Here's an example of a popular game (Hollow Knight) that uses horizontal choice buttons in its dialogue system:
![hollow-knight-dialogue-choice](https://user-images.githubusercontent.com/4451432/128618435-284043e8-095b-4c7c-809c-29d540935954.png)

**Comment by coppolaemilio** [comment] 2021-08-14 18:16
I will see if I can implement more customization to the options since it seems like a highly requested feature. Thanks for the detailed issue 🙌🏻

**Comment by coppolaemilio** [comment] 2021-08-14 19:35
Made a commit: https://github.com/coppolaemilio/dialogic/commit/6d365abb7ed4827f4a279cc6b25da9ce2ff16e69
If you get the latest version from `main` you should be able to select the orientation ( vertical or horizontal).

Let me know if that works! More settings will be added later 😅

**Comment by fmenozzi** [comment] 2021-08-14 23:24
The choice buttons don't seem to be visible on the current project I was using to test this out (at commit 6d365abb7ed4827f4a279cc6b25da9ce2ff16e69), though they are still functional (i.e. I can use the arrow keys to select choices and it behaves accordingly; I just can't see the choice buttons themselves).

However I was able to see that it's now possible to use horizontal choice button layouts on a completely fresh project at that same commit, so I guess something went wrong when my original test project updated to the new version of dialogic. I'll continue investigating that.

Thanks for adding this functionality! Looking forward to the additional settings.

**Comment by fmenozzi** [comment] 2021-08-15 00:05
The problems I ran into above are a good example of why it might be desirable from the user's viewpoint to be able to set custom choice button containers; they could set the padding, alignment, position on screen (e.g. center-top instead of center) themselves.

Depending on what additional settings you plan to add, this may not end up being strictly necessary in a lot of cases, but just thought I'd point it out.

**Comment by coppolaemilio** [comment] 2021-08-20 22:05
Pushed another fix to the element not being centered after resizing the window. So they should remain centered as I change the resolution. Let me know if it works on your end!

I believe that after adding some more positioning options for the buttons we won't need to add anything else.

You can always clone the Dialog.tscn and modify the type of container for the options, but it is my goal that this won't be necessary.

**Comment by fmenozzi** [comment] 2021-08-22 15:08
Happy to report that the horizontal option now correctly aligns my custom choice buttons centered horizontally, though interestingly enough the vertical option behaves differently now (the buttons are the width of the screen now instead the fixed width I had them at before; this happens even if I tick 'fixed button size' in the Choice Buttons section of the theme editor).

**Comment by coppolaemilio** [comment] 2021-09-13 14:02
@fmenozzi I added more options (anchor and offset) and I can't really reproduce the fixed button size bug. I'm going to close it for now, but feel free to open again if needed 👍🏻

**Closed by coppolaemilio** 2021-09-13 14:02 UTC
Labels: enhancement

**Comment by fmenozzi** [comment] 2021-09-14 00:29
Thanks a lot! The new options are a welcome addition, and I think the current HEAD doesn't have that fixed button size issue anymore.
