### ISSUE TITLE
Dialogic web export issue

### ISSUE THREAD

**Issue by ImperaEtConquer** [coppolaemilio/dialogic#914] opened 2022-06-02 20:32 UTC
## The problem

Dialogic never worked for me when I export my game as the web version. I didn't find a special guide for that in FAQ, therefore, I suppose that it should be working without any additional tweaks. As per the screenshots below, it looks like the game is not able to call Dialogic node relevant methods (in the addons/dialogic folder), although, I'm pretty sure I'm exporting every resource I have in my game project.

Therefore, I wonder, if it is even supposed to be working on the web? I'm currently testing it with the **1.4.2 - Dev version**.

![image](https://user-images.githubusercontent.com/20888857/171732666-46c5f4aa-1f0f-4a94-ad74-60e32bb0541e.png)

Desktop build screenshot
![image](https://user-images.githubusercontent.com/20888857/171732080-b403e782-7d71-43ea-bf3c-fa23ed32f6e8.png)

Web build
![image](https://user-images.githubusercontent.com/20888857/171732229-99852b4f-4334-4032-bf39-d3e18d2a6ec2.png)

**Comment by zaknafean** [comment] 2022-06-02 20:35
The current main branch (1.4.2) has many small fixes for exports, so start there. Not in that fix however is an issue we're hunting the root cause down for found here...

https://github.com/coppolaemilio/dialogic/issues/898#issuecomment-1140508911

More or less don't use the default theme, even in the settings, seems to help. It's seems to specifically be the default theme as well, since recreating the default theme as a new theme and using that doesn't seem to have the export problems

**Comment by ImperaEtConquer** [comment] 2022-06-02 20:42
Indeed, I tried another theme and it solved the issue. Thank you very much and sorry for the duplicated issue.

**Comment by zaknafean** [comment] 2022-06-02 20:43
Honestly it's just great so many people are moving far enough along in their projects with Dialogic that these issues are coming to light, and enough people are using it to also be finding workarounds.

We'll work on a more proper fix asap!

**Comment by zaknafean** [comment] 2022-06-02 20:45
Duplicate of #898

**Comment by zaknafean** [comment] 2022-07-05 16:22
Root caused by #915

**Comment by zaknafean** [comment] 2022-07-06 03:53
This and its dupes should be fixed with #978

**Closed by zaknafean** 2022-07-06 03:53 UTC
Labels: Bug 🐞
