### ISSUE TITLE
Definitions are only working partially

### ISSUE THREAD

**Issue by lacunoc** [coppolaemilio/dialogic#407] opened 2021-07-21 22:20 UTC
## The problem

**Describe the bug**
I've defined two definitions, PLAYER_NICKNAME and PLAYER_LETTER, but only PLAYER_NICKNAME works. It seems like, that every new added definition is not working anymore. Neither with the default value, nor any updated/set one.

**To Reproduce**
1. Go to Dialogic -> Definitions
2. Click on 'Add Value'
3. Create a new value with or without default value
4. Overwrite it via code
5. Create a timeline with [VARIABLE_NAME] as Text

**Expected behavior**
[VARIABLE_NAME] should be exchanged with the value of the variable

**Screenshots**
Code snippet
![image](https://user-images.githubusercontent.com/9279502/126566500-48855650-7977-4ce0-addc-813352547b72.png)

PLAYER_NICKNAME (in this case Alphabet) works
PLAYER_LETTER doesn't work (even without quotes)

**System (please complete the following information):**
 - OS: Windows 11 dev build
 - Godot Version: 3.3.2 stable
 - Dialogic Version: 1.2.4

## Solutions

**Workaround**

I've tried to delete and recreate the definition, tried different variable names, but as mentioned above, every new definition doesn't seem to work anymore.
Apparently this is a caching issue. Something was messed up and after removing C:\Users\USERNAME\AppData\Roaming\Godot\app_userdata\YOUR_PROJECT\dialogic folder all definitions are working as expected

**Possible fixes**

Clear caches properly when restarting the game.

**Comment by Jowan-Spooner** [comment] 2021-07-23 08:31
Hey thanks for reporting! 

I believe this is a duplicate of #267:
If you play your game at any point it will create a save of the definitions in the user:// directory. If you then load a game with reset_saves set to false it will load this older save. If you have created any definitions since then they wont be in the older save and thus not be shown correctly. You can see the correct result by setting reset_saves (second arguement of the Dialogic.start() function) to true. 

But yeah, you shouldn't have to do this. I will try to write this high into my priorities list as it is a game breaker.

Hope you can continue to work wirh dialogic!

**Comment by lacunoc** [comment] 2021-07-27 09:47
Hey Jowan-Spooner,
thanks for your response. I've retested this several times and I have to say, it's broken in both states. Setting reset_saves to True is not helping, I'm afraid.

Player _ready function
![image](https://user-images.githubusercontent.com/9279502/127133021-89b951cb-0bef-4d32-b892-67a8a97de5e4.png)

NPC dialog call
![image](https://user-images.githubusercontent.com/9279502/127133336-451e58e3-5d0b-4594-ba32-62aa62729a1c.png)

Excerpt dialog
![image](https://user-images.githubusercontent.com/9279502/127133535-4d831fd0-19fa-4256-978e-08f9e5dad5f7.png)

Dialog ingame
![image](https://user-images.githubusercontent.com/9279502/127133648-09cfcad7-1dbb-43f7-80e5-1b61babf3e01.png)

Even with reseting the saves and overwriting the default value, the default value is still shown, apparently. What can I do? Without this feature using dialogic is kind of useless, as I want to use many references of the game within my dialogues.

**Comment by Jowan-Spooner** [comment] 2021-07-27 12:20
Hey @lacunoc, I'm very sorry to hear it still doesn't work. I will try to have a look today what could cause this. You are right, this should be fixed as soon as possible.

**Comment by lacunoc** [comment] 2021-07-27 12:55
As a workaround I'm emitting a signal for every dialogue, where I need variables/definitions and using _on_dialog_signal with an "if" for the dialog_signal variable and set the Dialogic variables/definitions there. This works at least.
Something like this
```
func _on_dialog_signal(dialog_signal):
[...]
	if dialog_signal == "thief_check_for_weapons":
		Dialogic.set_variable("CHEST_LOOTED", vendor_chest_looted)
```

**Comment by Jowan-Spooner** [comment] 2021-07-27 13:35
Interesting. I think I found what causes your error but I'll have to test it a bit more. Sorry for your trouble.

**Comment by Jowan-Spooner** [comment] 2021-07-27 14:05
Hey @lacunoc I've pushed a fix to the main branch. Could you try if it works better now? Make to have the second parameter of Dialogic.start() to false so it won't reset to the defaults when starting the dialog.

**Comment by MerrMite** [comment] 2021-08-02 16:05
> Hey @lacunoc I've pushed a fix to the main branch. Could you try if it works better now? Make to have the second parameter of Dialogic.start() to false so it won't reset to the defaults when starting the dialog.

Thank you so much! This worked perfectly for me, I was having the exact same pass through issues

**Comment by coppolaemilio** [comment] 2021-08-29 01:03
I think this is fixed in the latest version. Feel free to reopen it if you still find errors.

**Closed by coppolaemilio** 2021-08-29 01:03 UTC
Labels: bug
