### ISSUE TITLE
Game don't open

### ISSUE THREAD

**Issue by kakurokan** [coppolaemilio/dialogic#913] opened 2022-06-01 20:37 UTC
## The problem

**Describe the bug**
My game simply don open, and when I see in the with debug versions, i see this.

**
![image](https://user-images.githubusercontent.com/67524990/171496946-05d0aeea-6345-4162-91b9-878355780346.png)
**

**Comment by zaknafean** [comment] 2022-06-01 21:33
Need more info. This an export? Windows? What version of dialogic?

**Comment by kakurokan** [comment] 2022-06-01 21:35
An export, Windows 10 and version 1.4.1. Sorry for that.

**Comment by kakurokan** [comment] 2022-06-01 21:47
Thank you, it's the problem of this comment. I will check

**Comment by zaknafean** [comment] 2022-06-02 20:44
Duplicate of #898

**Closed** 2022-06-18 21:08 UTC
