### ISSUE TITLE
Folders in timelines, characters, definitions

### ISSUE THREAD

**Issue by 77HriP77** [coppolaemilio/dialogic#282] opened 2021-05-04 09:07 UTC
WARNING: This is google translate :) sorry.
 
If the project is large and there are a lot of dialogues / plot developments planned in it, then it is very difficult to sort all this. You can, of course, make the names "parameter_parameter_more". But it would be very convenient if it could be done in folders, as in godo itself.

The ability to add an empty dialog node to another scene is still sorely lacking. I don't know how technically difficult it is to accomplish, since this is a whole scene with a huge amount of code, but it would be convenient if I could make a lot of such scenes. And just copy the characters there and develop another huge branch of events.

And finally, you are great! I've looked at a lot of dialog addons, yours is the friendliest!)

**Comment by Jowan-Spooner** [comment] 2021-05-04 09:56
The folders part is a duplicate of  #111. I'm not sure what you mean with adding an empty DialogNode.

**Comment by 77HriP77** [comment] 2021-05-04 10:49
> I'm not sure what you mean with adding an empty DialogNode.

I will try to explain in more detail. I have a main scene (node2d) and I added a dialogic scene to it. I created a lot of storylines there, and I'm moving on to developing a new scene. And I want to add another dialogic there, empty as a new project, just in another scene. To separate the storylines.

**Comment by coppolaemilio** [comment] 2021-05-05 16:30
This will not be a feature because Dialogic is global. Having separated folders will be possible but if you want to have different Dialogic instances for each scene you would need to make different projects for each scene. I'll be closing this one now because when folders are added this won't be really needed.

**Closed by coppolaemilio** 2021-05-05 16:30 UTC
Labels: enhancement
