### ISSUE TITLE
Visual Novel Layout Doesn't Allow for Adjusting Below Default Size

### ISSUE THREAD

**Issue by jlillie3** [coppolaemilio/dialogic#1897] opened 2023-11-11 14:36 UTC
We tried to use this for a low res pixel art game. Our resolution is normally 320 x 180. Changing the dialog box size for the Visual Novel layout doesn't let it go below the default size of 550 x 110

**To Reproduce**
1. Change project resolution to 320 x 180, with stretch mode set to Canvas Items
2. Edit Dialogic Styles
3. Change to something reasonable within the resolution
4. Dialog box is huge

The RPG layout seems to work properly

**Screenshots**
![image](https://github.com/coppolaemilio/dialogic/assets/98480564/d4845afb-ba2a-45fa-bf80-d6dca401841e)
![image](https://github.com/coppolaemilio/dialogic/assets/98480564/b3d52540-e6cb-43d5-8f0b-857cbede82da)

**System (please complete the following information):**
 Godot version 4.1.3

**Comment by Jowan-Spooner** [comment] 2023-11-11 14:38
Thanks for the report. This is kinda a duplicate of #1837, but I will leave this, as it has more information.
I'll likely sort out all of the layout mess for the next update as I'm trying to focus on a big layout update anyways.

**Comment by Jowan-Spooner** [comment] 2023-12-06 14:55
The whole layout has been reworked so this is outdated.

**Closed by Jowan-Spooner** 2023-12-06 14:55 UTC
Labels: Bug 🐞, Planned
