### ISSUE TITLE
Custom portrait scene disappears after fade in time

### ISSUE THREAD

**Issue by bitbrain** [coppolaemilio/dialogic#805] opened 2022-02-28 20:20 UTC
## The problem

When configuring a portrait with a custom scene, for example by using AnimatedSprite, the fade in effect does not seem to work. Instead, the avatar disappears after a said interval:

![dwarf](https://user-images.githubusercontent.com/822035/156052617-b1e9572f-3a3d-44fd-99e7-f74d29ff8daf.gif)

**To Reproduce**
1. create a custom scene of type AvatarFrames
2. assign custom scene as default portrait for dialogue
3. use dialogue in timeline

**Expected behavior**
The portrait should tween in as expected and additionally should stay.

**Actual Behaviour**

The portrait instantly appears and then disappears after some time.

**System (please complete the following information):**
 - OS: Windows
 - Godot Version: 3.4.2
 - Dialogic Version: 1.4.DEV

**Comment by coppolaemilio** [comment] 2022-03-01 08:25
@bitbrain I'm having issues reproducing this one. Can you send me a screenshot of the custom portrait node structure? or is it just a simple AnimatedSprite?

**Comment by bitbrain** [comment] 2022-03-01 08:34
Hey @coppolaemilio - an update on this: this is happening because I first set the animation to 'Default' and then have a secondary branch check where I set it explicitly to 'Neutral', however, the 'Neutral' expression does not exist anymore (I removed it)
![Capture](https://user-images.githubusercontent.com/822035/156133210-d84d2d3c-b006-4b3d-9452-6c4eddc69b21.JPG)

A few things from this:

- it is interesting that the behaviour seems to be different between 1.3 and 1.4 (in 1.3 the character does not seem to appear at all)
- this does not seem to be a _bug_ but rather a problem of users removing emotions from the character menu but then having timelines still referencing that emotion

A few suggestions on how to solve this:

a. Ignore it (current behaviour)
b. log an error to highlight the bad configuration
c. default to the 'Default' portrait in case the one configured cannot be found (and optionally, log an error)

**Comment by coppolaemilio** [comment] 2022-03-01 08:39
> this does not seem to be a bug but rather a problem of users removing emotions from the character menu but then having timelines still referencing that emotion

I'll make it so that it can show a warning on the terminal and go to the 'Default' portrait when they removed the one selected in the timeline.

PS: Gotta fix also the style of the events in 200% render scale lol 🙈

**Comment by coppolaemilio** [comment] 2022-03-01 22:53
Implemented a warning that looks like this:
![image](https://user-images.githubusercontent.com/2206700/156262372-64649b75-4c3e-4bde-b60c-2b1e410fb5ba.png)

And now it will properly set to the default expression when the one selected in the timeline doesn't exists any more. The code was only defaulting to regular image portraits, but it now should also select scenes. 

I'll close the issue but feel free to re-open it if it is not working for you!

**Closed by coppolaemilio** 2022-03-01 22:53 UTC
Labels: Bug 🐞
