### ISSUE TITLE
Translation system doesn't localize characters yet

### ISSUE THREAD

**Issue by DancingEngie** [coppolaemilio/dialogic#1823] opened 2023-10-22 22:17 UTC
**Is your feature request related to a problem? Please describe.**
The translation system works for dialogues, but it does not appear to support character names. This leads to a strange scenario where the dialogue is in one language, but the character name is still in English.

**Describe the solution you'd like**
Add keys for character names, so they can be properly localized.

**Describe alternatives you've considered**
My current hacky solution is to create a key and a translated moniker for a character in another file, then paste that key into that character's "display name" field. The UI label automatically localizes that key, which circumvents the issue - but it's not optimal and requires one to juggle between two (or more) files.

**Additional context**
N/A

**Comment by Jowan-Spooner** [comment] 2023-10-23 04:29
Thanks for the report. This is kind of a duplicate of #1490, but I will keep it for now.

**Comment by DancingEngie** [comment] 2023-10-23 13:11
> Thanks for the report. This is kind of a duplicate of #1490, but I will keep it for now.

Fair enough, didn't notice that. Feel free to merge my request if you like.

**Closed** 2023-11-30 11:34 UTC
Labels: Feature✨
