### ISSUE TITLE
Changing scale properties in dialogic characters does not work

### ISSUE THREAD

**Issue by Yotopihi-Dev** [coppolaemilio/dialogic#1256] opened 2022-10-19 09:36 UTC
You can change scales in the portrait holder scene, and in the dialogic character settings, but the properties won't save, as a result, won't ever change the scale. 

I also get the error 'drivers/windows/file_access_windows.cpp:312 - Condition "fwrite(p_src, 1, p_length, f) != (size_t)p_length" is true.'

**To Reproduce**:
1. Go to either the dialogic portrait holder scene or character settings
2. Then change the scale and save it
3. You won't see anything changing

**Expected behavior**:
The portrait scale to change in dialog prompts

![unknown (4)](https://user-images.githubusercontent.com/101610280/196653322-44d03608-6160-4653-9e1f-40f00fa23e29.png)

This happens on:
-  Windows
 - Godot Version: 4.0 beta 2
 - Dialogic Version: 2.0 for beta 2

A workaround is closing your project and opening the .dch file in notepad or text editor and then optimizing the scale in there

**Possible fixes**:

Godot 4.0 beta 2 has a new way to write files 

[https://godotengine.org/article/dev-snapshot-godot-4-0-beta-2](https://godotengine.org/article/dev-snapshot-godot-4-0-beta-2)

So by chance, when the character is being saved (resulting in writing a file) you're not following Godot's new file syntax

This is initially how you would write a file in previous versions

`var file = File.new()
if not file.file_exists("user://save_game.dat"):
    file.open("user://save_game.dat", File.WRITE)
    file.store_var(user_data)
    file.close()`

And this is the new way in Godot 4.0 beta 2

`if not FileAccess.file_exists("user://save_game.dat"):
    var file = FileAccess.open("user://save_game.dat", FileAccess.WRITE)
    file.store_var(user_data)`

**Comment by thebardsrc** [comment] 2022-10-19 13:34
gonna assign to myself, because I was gonna go over and check everything with saving in #1255. there does seem to be an actual bug with saving too tho which I'm investigating to raise with Godot.

**Comment by Jowan-Spooner** [comment] 2022-10-24 08:16
Can't recreate. Make sure that you are pressing enter after writing in the new value. Godots SpinBox doesn't really handle changes well. 
Could you retry if you can still reproduce it?

**Comment by Yotopihi-Dev** [comment] 2022-10-24 12:10
I can't, after the commit bardsrc did, saving characters worked just fine. And yes, I did press enter

**Closed** 2022-10-24 12:10 UTC
Labels: Bug 🐞, Critical 💩
